image: node:10-slim

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/

tests:
  stage: test
  before_script:
  - apt-get install git
  - npm i -g yarn
  - yarn install
  script:
  - yarn style:check
  - yarn coverage:cover
  - ls -al

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
