image: node:10-slim

stages:
- build
- test
- deploy

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/

# test:node-10:
#   image: node:10-alpine
#   stage: test
#   before_script:
#   - npm i -g yarn
#   - yarn install
#   script:
#   - yarn style:check
#   - yarn coverage:cover

# test:node-8:
#   image: node:8-alpine
#   stage: test
#   before_script:
#   - npm i -g yarn
#   - yarn install
#   script:
#   - yarn style:check
#   - yarn coverage:cover

versioning:
  stage: deploy
  before_script:
  - apt-get update -qq && apt-get install -qq -y git
  - npm i -g yarn
  - yarn install
  script:
  - yarn build:ci
  - yarn start
  - sh build.sh
  - cat package.json
  only:
  - master

# pages:
#   stage: deploy
#   script:
#   - npm i
#   - npm run build:docs
#   - mkdir .public
#   - cp -r docs/* .public
#   - mv .public public
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
