image: node:10-slim

stages:
  - style
  - test
  - versioning
  - npm_deploy
  - docker_deploy

before_script:
  - npm install

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

style:
  image: node:10-alpine
  stage: style
  script:
    - npm run style:check
  except:
    - tags

1:2 coverage:
  image: node:10-alpine
  stage: test
  script:
    - npm run test:cover
  except:
    - tags

2:2 coverage:
  image: node:12-alpine
  stage: test
  script:
    - npm run test:cover
  except:
    - tags

coverage:report:
  image: node:12
  stage: test
  script:
    - npm run test:cover
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}" -f coverage/*.json
  only:
    - tags

versioning:
  stage: versioning
  image: priestine/semantics:latest
  script:
    - priestine-semantics --private-token=${SEMANTICS_TOKEN} --project-path=priestine/semantics
  only:
    - master

deploy:npm:
  stage: npm_deploy
  script:
    - bash deploy_npm.sh
  only:
    - tags

publish:docker:
  stage: docker_deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  before_script:
    - echo ""
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t priestine/semantics:${CI_COMMIT_REF_NAME}-alpine - < ./docker/alpine.Dockerfile
    - docker build -t priestine/semantics:latest - < ./docker/alpine.Dockerfile
    - docker build -t priestine/semantics:alpine - < ./docker/alpine.Dockerfile
    - docker build -t priestine/semantics:${CI_COMMIT_REF_NAME}-slim - < ./docker/slim.Dockerfile
    - docker build -t priestine/semantics:slim - < ./docker/slim.Dockerfile
    - docker push priestine/semantics
  only:
    - tags
