image: node:10-slim

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/

tests:
  stage: test
  before_script:
  - apt-get update -qq && apt-get install -qq -y git
  - npm i -g yarn
  - yarn install
  script:
  - yarn style:check
  - yarn coverage:cover
  - yarn build:ci
  - yarn start

