sudo: false
language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules

stages:
  - check
  - name: cover
    if: branch = master AND type = push
  - name: versioning
    if: branch = master AND type = push
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: check
      script:
        - npm run lint
        - npm run test
    - stage: cover
      script:
        - npm run test:cover
        - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}" -f coverage/*.json
    - stage: versioning
      script:
        - npm i -g @priestine/semantics@5.1.1
        - priestine-semantics
    - stage: publish
      services:
        - docker
      script:
        - bash deploy_npm.sh
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
        - docker build -t priestine/semantics:${TRAVIS_TAG}-alpine - < ./docker/alpine.Dockerfile
        - docker build -t priestine/semantics:${TRAVIS_TAG} - < ./docker/alpine.Dockerfile
        - docker build -t priestine/semantics:latest - < ./docker/alpine.Dockerfile
        - docker build -t priestine/semantics:alpine - < ./docker/alpine.Dockerfile
        - docker build -t priestine/semantics:${TRAVIS_TAG}-slim - < ./docker/slim.Dockerfile
        - docker build -t priestine/semantics:slim - < ./docker/slim.Dockerfile
        - docker push priestine/semantics

